name = "Mnemonic Realms"

modules = [
    './main',
    '@rpgjs/default-gui',
    '@rpgjs/gamepad'
]

[start]
    map = 'overworld'
    graphic = 'hero'
    hitbox = [16, 16]

[compilerOptions.build]
    pwaEnabled = false
