name = "Mnemonic Realms"

modules = [
    '@rpgjs/default-gui',
    '@rpgjs/gamepad',
    './main'
]

[start]
    map = 'overworld'
    graphic = 'hero'
    hitbox = [16, 16]

[inputs.action]
    name = "action"
    bind = ["space", "enter", "click"]

[inputs.back]
    name = "back"
    bind = ["escape", "backspace"]

[compilerOptions.build]
    pwaEnabled = false

[vite.optimizeDeps]
    include = ["sat"]
