name = "Mnemonic Realms"

modules = [
    './main',
    '@rpgjs/default-gui',
    '@rpgjs/gamepad'
]

[start]
    map = 'overworld'
    graphic = 'hero'
    hitbox = [16, 16]

[inputs.action]
    name = "action"
    bind = ["space", "enter", "click"]

[inputs.back]
    name = "back"
    bind = ["escape", "backspace"]

[compilerOptions.build]
    pwaEnabled = false
